source 'https://rubygems.org'

ruby '2.2.3'

gem 'heroku-bouncer', '0.0.1'
gem 'sinatra-contrib'
gem 'thin'
gem 'slim'
gem 'compass'
gem 'http_parser.rb', :git => 'https://github.com/tmm1/http_parser.rb.git', :branch => 'latest-upstream'
gem 'eventmachine'
gem 'em-http-request', '~>1.0'
gem 'json'
gem 'rack-flash3'
gem "stethoscope", :git => 'https://github.com/raulb/stethoscope.git'
